//register
export const USER_REQUEST = "USER_REQUEST";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_FAILURE = "USER_FAILURE";
export const USER_SAVED_SUCCESS = "USER_SAVED_SUCCESS";


// login
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";



// get API

// -- user
export const GET_USER_BY_ID = "GET_USER_BY_ID";

// -- resource
export const GET_RESOURCE_SUCCESS = "GET_RESOURCE_SUCCESS";
export const GET_RESOURCE_REQUEST = "ET_RESOURCE_REQUEST";
export const GET_RESOURCE_FAILURE = "GET_RESOURCE_FAILURE";
export const GET_RESOURCE_SAVED_SUCCESS = "GET_RESOURCE_SAVED_SUCCESS";